### ISSUE TITLE
[ERROR] Only alphanumeric characters and underscores are allowed in the id

### ISSUE THREAD

**Issue by Greatz08** [thearyadev/youtube-transcript-provider#1]
I guess code update needed so reporting here  :-))

![20241029_19h17m24s_grim](https://github.com/user-attachments/assets/1733dd4d-6563-4543-be89-4c0b2496e4b0)

**Comment by thearyadev** [comment]
thanks for the report! i will look into it.

**Comment by thearyadev** [comment]
ok so it seems that error is because of the id of the tool. 
`youtube_transcript_provider_(langchain_community)`
the name cant include `(` or `)`. 

`youtube_transcript_provider_lc` should work fine.
